### ISSUE TITLE
Ubuntu で実行した時、TARGET_DIR の設定チェックが動作しません

### ISSUE THREAD

**Issue by smeghead** [blue-goheimochi/php-metrics-tools#1]
便利なツールを公開していただきありがとうございます。

環境変数を指定せずに、`make phpstan` を実行した時、`/bin/sh: 1: [[: not found` が表示されて、チェックを抜けてdockerコマンドを実行してしまっているようです。

```bash
$ make phpstan
/bin/sh: 1: [[: not found
TARGET_DIR: 
docker: invalid spec: :/app:ro: empty section between colons.
See 'docker run --help'.
make: *** [Makefile:33: phpstan] エラー 125
```

環境は、OS: Ubuntu 22.04.3 LTS です。

試しにMakefileの先頭に、`SHELL=bash` の行を追加したところ、Ubuntuではチェックが正しく動作しました。

**Comment by blue-goheimochi** [comment]
@smeghead 

ご連絡ありがとうございます！！ 🙏 

たしかにチェックを抜けてしまうことを確認しました 🙇 
（Macでしか動作確認しておりませんでした…）

 `if` の書き方、変数参照の仕方、あたりをPOSIX互換の記述に変更することで対応ができそうなので、そのような形で修正してみたいと思います。

**Comment by blue-goheimochi** [comment]
@smeghead 
こちら修正をマージしましたので、隙がありましたらお試ししてみていただければ幸いです 🙇

**Comment by smeghead** [comment]
@blue-goheimochi 
ありがとうございます。手元のUbuntu環境で環境変数を指定せずに実行したときに、環境変数のチェックが正しく動作し、dockerコマンドの実行が行なわれないことが確認できました。
問題がなくなっていることが確認できました。

**Comment by blue-goheimochi** [comment]
@smeghead 
ご確認ありがとうございました 🙏 
ご報告もありがとうございましたーIssueクローズさせていただきます！！ 🙇
